[package]
name = "rusty-psn"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.10.1"
reqwest = "0.11.9"
crossterm = "0.23.0"
tokio = { version = "1.17.0", default-features = false, features = ["rt", "io-util", "macros", "fs"] }
