name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux-cli-build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build rusty-psn (linux-cli)
      run: cargo build --release --no-default-features --features "cli"
    - name: Move binary
      run: |
        mkdir result
        cp target/release/rusty-psn result
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rusty-psn-linux
        path: result

  linux-egui-build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install egui deps
      run: sudo apt update && sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
    - name: Build rusty-psn (linux-egui)
      run: cargo build --release --no-default-features --features "egui"
    - name: Move binary
      run: |
        mkdir result
        cp target/release/rusty-psn result
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rusty-psn-linux
        path: result
        
  windows-cli-build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build rusty-psn (windows-egui)
      run: cargo build --release --no-default-features --features "cli"
    - name: Move binary
      run: |
        mkdir result
        copy target/release/rusty-psn.exe result 
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rusty-psn-windows
        path: result 

  windows-egui-build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build rusty-psn (windows-egui)
      run: cargo build --release --no-default-features --features "egui"
    - name: Move binary
      run: |
        mkdir result
        copy target/release/rusty-psn.exe result 
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rusty-psn-windows
        path: result 
